import { expect, it, vi } from "vitest";
import { runImplementationPhase } from "../executor/run-implementation-phase.js";
import { createTaskDoneTool } from "../executor/create-task-done-tool.js";
function fixture(){
 const task:any={id:"CENSUS-COMPLETION",title:"Synthetic completion",description:"Synthetic",column:"in-progress",dependencies:[],steps:[{name:"done",status:"done"},{name:"required",status:"in-progress"}],currentStep:1,log:[],prompt:"# Synthetic",createdAt:"2026-09-13T00:00:00Z",updatedAt:"2026-09-13T00:00:00Z"};
 const writes:string[]=[];const store:any={getTask:vi.fn(async()=>task),getSettings:vi.fn(async()=>({})),getWorkflowSelection:vi.fn(async()=>null),getWorkflowDefinition:vi.fn(async()=>undefined),updateStep:vi.fn(async(_id,i,status)=>{task.steps[i].status=status;writes.push("step");}),updateTask:vi.fn(async(_id,p)=>{Object.assign(task,p);writes.push("task");return task;}),logEntry:vi.fn(async()=>{})};
 const onDone=vi.fn();const deps:any={store,getRunContextFor:()=>undefined,workflowLifecycleMovesInFlight:new Set(),persistTokenUsage:vi.fn(),getTaskCompletionBlocker:vi.fn(async()=>undefined),evaluateTaskVerdictProviders:vi.fn(async()=>({ok:true})),verifyWorktreeInvariants:vi.fn(async()=>({ok:true})),evaluateTaskDoneScopeLeak:vi.fn(async()=>({blocked:false})),scheduleCompletedTaskWatchdog:vi.fn(),finalizeAcceptedNoOpCompletion:vi.fn()};
 const tool=createTaskDoneTool(deps,task.id,"/synthetic","# Synthetic",new Map([[1,"APPROVE"]]),onDone);
 return {task,store,onDone,tool,writes};
}
it("control: successful completion writes steps and signals exactly once",async()=>{const f=fixture();await f.tool.execute("fixture",{summary:"complete"});expect(f.task.steps[1].status).toBe("done");expect(f.onDone).toHaveBeenCalledOnce();expect(f.store.updateTask).toHaveBeenCalled();});
it("control: one implementation callback retains its actual file payload",async()=>{const {task}=fixture();const r=await runImplementationPhase({runImplementation:async(_task,complete)=>complete({modifiedFiles:["one.ts"]})},task);expect(r).toEqual({taskDone:true,modifiedFiles:["one.ts"]});});
it("a duplicate completion cannot replace the first accepted payload",async()=>{const {task}=fixture();const r=await runImplementationPhase({runImplementation:async(_task,complete)=>{complete({modifiedFiles:["one.ts"]});complete({modifiedFiles:["late.ts"]});}},task);expect(r.modifiedFiles).toEqual(["one.ts"]);});
it("required persistence rejection cannot announce completion",async()=>{const f=fixture();f.store.updateStep.mockRejectedValue(new Error("required write rejected"));const r=await f.tool.execute("fixture",{summary:"complete"}).then(()=>null,e=>e.message);expect(r).toBe("required write rejected");expect(f.store.updateStep).toHaveBeenCalled();expect(f.onDone).not.toHaveBeenCalled();});
it("a completion callback observes already-written required state",async()=>{const f=fixture();let observed:string|undefined;f.onDone.mockImplementation(()=>{observed=f.task.steps[1].status;});await f.tool.execute("fixture",{summary:"complete"});expect(observed).toBe("done");});
it("optional diagnostic failure cannot revoke persisted completion",async()=>{const f=fixture();f.store.logEntry.mockRejectedValue(new Error("optional diagnostic unavailable"));await f.tool.execute("fixture",{}).catch(()=>{});expect(f.task.steps[1].status).toBe("done");expect(f.onDone).toHaveBeenCalledOnce();});